# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/blakeziegler/tech/projects/zchain

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/blakeziegler/tech/projects/zchain

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/blakeziegler/tech/projects/zchain/CMakeFiles /Users/blakeziegler/tech/projects/zchain//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/blakeziegler/tech/projects/zchain/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ozone

# Build rule for target.
ozone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ozone
.PHONY : ozone

# fast build rule for target.
ozone/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/build
.PHONY : ozone/fast

block_arc/block.o: block_arc/block.cpp.o
.PHONY : block_arc/block.o

# target to build an object file
block_arc/block.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/block.cpp.o
.PHONY : block_arc/block.cpp.o

block_arc/block.i: block_arc/block.cpp.i
.PHONY : block_arc/block.i

# target to preprocess a source file
block_arc/block.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/block.cpp.i
.PHONY : block_arc/block.cpp.i

block_arc/block.s: block_arc/block.cpp.s
.PHONY : block_arc/block.s

# target to generate assembly for a file
block_arc/block.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/block.cpp.s
.PHONY : block_arc/block.cpp.s

block_arc/blockchain.o: block_arc/blockchain.cpp.o
.PHONY : block_arc/blockchain.o

# target to build an object file
block_arc/blockchain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/blockchain.cpp.o
.PHONY : block_arc/blockchain.cpp.o

block_arc/blockchain.i: block_arc/blockchain.cpp.i
.PHONY : block_arc/blockchain.i

# target to preprocess a source file
block_arc/blockchain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/blockchain.cpp.i
.PHONY : block_arc/blockchain.cpp.i

block_arc/blockchain.s: block_arc/blockchain.cpp.s
.PHONY : block_arc/blockchain.s

# target to generate assembly for a file
block_arc/blockchain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/blockchain.cpp.s
.PHONY : block_arc/blockchain.cpp.s

block_arc/hash_utils.o: block_arc/hash_utils.cpp.o
.PHONY : block_arc/hash_utils.o

# target to build an object file
block_arc/hash_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/hash_utils.cpp.o
.PHONY : block_arc/hash_utils.cpp.o

block_arc/hash_utils.i: block_arc/hash_utils.cpp.i
.PHONY : block_arc/hash_utils.i

# target to preprocess a source file
block_arc/hash_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/hash_utils.cpp.i
.PHONY : block_arc/hash_utils.cpp.i

block_arc/hash_utils.s: block_arc/hash_utils.cpp.s
.PHONY : block_arc/hash_utils.s

# target to generate assembly for a file
block_arc/hash_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/hash_utils.cpp.s
.PHONY : block_arc/hash_utils.cpp.s

block_arc/ipfs_utils.o: block_arc/ipfs_utils.cpp.o
.PHONY : block_arc/ipfs_utils.o

# target to build an object file
block_arc/ipfs_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/ipfs_utils.cpp.o
.PHONY : block_arc/ipfs_utils.cpp.o

block_arc/ipfs_utils.i: block_arc/ipfs_utils.cpp.i
.PHONY : block_arc/ipfs_utils.i

# target to preprocess a source file
block_arc/ipfs_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/ipfs_utils.cpp.i
.PHONY : block_arc/ipfs_utils.cpp.i

block_arc/ipfs_utils.s: block_arc/ipfs_utils.cpp.s
.PHONY : block_arc/ipfs_utils.s

# target to generate assembly for a file
block_arc/ipfs_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/ipfs_utils.cpp.s
.PHONY : block_arc/ipfs_utils.cpp.s

block_arc/main.o: block_arc/main.cpp.o
.PHONY : block_arc/main.o

# target to build an object file
block_arc/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/main.cpp.o
.PHONY : block_arc/main.cpp.o

block_arc/main.i: block_arc/main.cpp.i
.PHONY : block_arc/main.i

# target to preprocess a source file
block_arc/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/main.cpp.i
.PHONY : block_arc/main.cpp.i

block_arc/main.s: block_arc/main.cpp.s
.PHONY : block_arc/main.s

# target to generate assembly for a file
block_arc/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/main.cpp.s
.PHONY : block_arc/main.cpp.s

block_arc/proof_of_work.o: block_arc/proof_of_work.cpp.o
.PHONY : block_arc/proof_of_work.o

# target to build an object file
block_arc/proof_of_work.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/proof_of_work.cpp.o
.PHONY : block_arc/proof_of_work.cpp.o

block_arc/proof_of_work.i: block_arc/proof_of_work.cpp.i
.PHONY : block_arc/proof_of_work.i

# target to preprocess a source file
block_arc/proof_of_work.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/proof_of_work.cpp.i
.PHONY : block_arc/proof_of_work.cpp.i

block_arc/proof_of_work.s: block_arc/proof_of_work.cpp.s
.PHONY : block_arc/proof_of_work.s

# target to generate assembly for a file
block_arc/proof_of_work.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/proof_of_work.cpp.s
.PHONY : block_arc/proof_of_work.cpp.s

block_arc/transaction.o: block_arc/transaction.cpp.o
.PHONY : block_arc/transaction.o

# target to build an object file
block_arc/transaction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/transaction.cpp.o
.PHONY : block_arc/transaction.cpp.o

block_arc/transaction.i: block_arc/transaction.cpp.i
.PHONY : block_arc/transaction.i

# target to preprocess a source file
block_arc/transaction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/transaction.cpp.i
.PHONY : block_arc/transaction.cpp.i

block_arc/transaction.s: block_arc/transaction.cpp.s
.PHONY : block_arc/transaction.s

# target to generate assembly for a file
block_arc/transaction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ozone.dir/build.make CMakeFiles/ozone.dir/block_arc/transaction.cpp.s
.PHONY : block_arc/transaction.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ozone"
	@echo "... block_arc/block.o"
	@echo "... block_arc/block.i"
	@echo "... block_arc/block.s"
	@echo "... block_arc/blockchain.o"
	@echo "... block_arc/blockchain.i"
	@echo "... block_arc/blockchain.s"
	@echo "... block_arc/hash_utils.o"
	@echo "... block_arc/hash_utils.i"
	@echo "... block_arc/hash_utils.s"
	@echo "... block_arc/ipfs_utils.o"
	@echo "... block_arc/ipfs_utils.i"
	@echo "... block_arc/ipfs_utils.s"
	@echo "... block_arc/main.o"
	@echo "... block_arc/main.i"
	@echo "... block_arc/main.s"
	@echo "... block_arc/proof_of_work.o"
	@echo "... block_arc/proof_of_work.i"
	@echo "... block_arc/proof_of_work.s"
	@echo "... block_arc/transaction.o"
	@echo "... block_arc/transaction.i"
	@echo "... block_arc/transaction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

